coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        base: auto
        threshold: 2%
        paths:
          - "src"
    patch:
      default:
        target: 90%
        threshold: 2%
